package com.yanerdan.venueflow.auth.application;

public enum AuthErrorCode {
  AUTH_USERNAME_EXISTS,
  AUTH_INVALID_CREDENTIALS,
  AUTH_INVALID_REFRESH_TOKEN,
  AUTH_FORBIDDEN,
  AUTH_ACCOUNT_NOT_FOUND,
  AUTH_ROLE_CONFLICT,
  AUTH_PROVIDER_UNAVAILABLE,
  AUTH_EXTERNAL_LOGIN_INVALID,
  AUTH_PERSISTENCE_FAILURE
}
