package com.yanerdan.venueflow.resource.catalog.error;

public enum CatalogErrorCode {
  VALIDATION_ERROR,
  CATEGORY_ALREADY_EXISTS,
  CATEGORY_NOT_FOUND,
  RESOURCE_NUMBER_ALREADY_EXISTS,
  RESOURCE_NOT_FOUND,
  INVALID_RESOURCE_STATUS_TRANSITION,
  OPTIMISTIC_LOCK_CONFLICT,
  CATALOG_PERSISTENCE_ERROR,
  INTERNAL_ERROR
}
