package com.yanerdan.venueflow.resource.catalog.error;

public enum CatalogErrorCode {
  VALIDATION_ERROR,
  CATEGORY_ALREADY_EXISTS,
  CATEGORY_NOT_FOUND,
  RESOURCE_NUMBER_ALREADY_EXISTS,
  RESOURCE_NOT_FOUND,
  RESOURCE_NOT_ACTIVE_FOR_SLOT,
  RESOURCE_SLOT_NOT_FOUND,
  INVALID_SLOT_TIME_RANGE,
  RESOURCE_SLOT_TIME_OVERLAP,
  INVALID_RESOURCE_STATUS_TRANSITION,
  INVALID_RESOURCE_SLOT_STATUS_TRANSITION,
  OPTIMISTIC_LOCK_CONFLICT,
  RESOURCE_SLOT_NOT_OPEN_FOR_ALLOCATION,
  INSUFFICIENT_SLOT_CAPACITY,
  RELEASE_EXCEEDS_OCCUPIED_CAPACITY,
  ALLOCATION_OPERATION_CONFLICT,
  CATALOG_PERSISTENCE_ERROR,
  INTERNAL_ERROR
}
