spring:
  application:
    name: venueflow-auth-service
  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  profiles:
    default: skeleton
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

server:
  port: ${SERVER_PORT:8081}

management:
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    enabled: false
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health
      discovery:
        enabled: false
    jmx:
      exposure:
        exclude: "*"

  endpoint:
    health:
      access: read-only
      show-details: never
      show-components: never
      probes:
        enabled: true
