spring:
  config:
    activate:
      on-profile: skeleton
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
      - org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration
      - org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.security.autoconfigure.web.servlet.SecurityFilterAutoConfiguration
      - org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration
      - org.springframework.boot.security.autoconfigure.actuate.web.servlet.ManagementWebSecurityAutoConfiguration
