spring:
  application:
    name: venueflow-auth-service
  profiles:
    default: skeleton

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health
      discovery:
        enabled: false
    jmx:
      exposure:
        exclude: "*"

  endpoint:
    health:
      access: read-only
      show-details: never
      show-components: never
      probes:
        enabled: true
