package com.yanerdan.venueflow.booking.domain;

import java.time.LocalDateTime;

public record BookingReservation(
    Long id,
    String bookingNo,
    String requestId,
    long userId,
    long slotId,
    int quantity,
    BookingStatus status,
    String allocationOperationId,
    String releaseOperationId,
    long version,
    LocalDateTime createdAt,
    LocalDateTime expireAt,
    LocalDateTime confirmedAt,
    LocalDateTime cancelledAt,
    LocalDateTime expiredAt,
    LocalDateTime completedAt,
    String terminalReason,
    LocalDateTime updatedAt,
    String activityTitle,
    String applicationPurpose,
    String contactName,
    String contactPhone,
    String applicationNote,
    String reviewDecision,
    String reviewNote,
    String reviewerRole,
    LocalDateTime reviewedAt,
    Long resourceId,
    String ownerDepartment,
    String assignedApproverExternalUserId,
    String approvalMode,
    String finalAssignedApproverExternalUserId,
    int currentApprovalStep) {
  public BookingReservation(
      Long id,
      String bookingNo,
      String requestId,
      long userId,
      long slotId,
      int quantity,
      BookingStatus status,
      String allocationOperationId,
      String releaseOperationId,
      long version,
      LocalDateTime createdAt,
      LocalDateTime expireAt,
      LocalDateTime confirmedAt,
      LocalDateTime cancelledAt,
      LocalDateTime expiredAt,
      LocalDateTime completedAt,
      String terminalReason,
      LocalDateTime updatedAt) {
    this(
        id, bookingNo, requestId, userId, slotId, quantity, status, allocationOperationId,
        releaseOperationId, version, createdAt, expireAt, confirmedAt, cancelledAt, expiredAt,
        completedAt, terminalReason, updatedAt, null, null, null, null, null, null, null, null,
        null, null, null, null, "DIRECT", null, 1);
  }

  public BookingReservation(
      Long id,
      String bookingNo,
      String requestId,
      long userId,
      long slotId,
      int quantity,
      BookingStatus status,
      String allocationOperationId,
      String releaseOperationId,
      long version,
      LocalDateTime createdAt,
      LocalDateTime expireAt,
      LocalDateTime confirmedAt,
      LocalDateTime cancelledAt,
      LocalDateTime expiredAt,
      String terminalReason,
      LocalDateTime updatedAt) {
    this(
        id,
        bookingNo,
        requestId,
        userId,
        slotId,
        quantity,
        status,
        allocationOperationId,
        releaseOperationId,
        version,
        createdAt,
        expireAt,
        confirmedAt,
        cancelledAt,
        expiredAt,
        null,
        terminalReason,
        updatedAt,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null, null, null, null, "DIRECT", null, 1);
  }

  public BookingReservation(
      Long id,
      String bookingNo,
      String requestId,
      long userId,
      long slotId,
      int quantity,
      BookingStatus status,
      String allocationOperationId,
      String releaseOperationId,
      long version,
      LocalDateTime createdAt,
      LocalDateTime confirmedAt,
      LocalDateTime cancelledAt,
      LocalDateTime updatedAt) {
    this(
        id,
        bookingNo,
        requestId,
        userId,
        slotId,
        quantity,
        status,
        allocationOperationId,
        releaseOperationId,
        version,
        createdAt,
        null,
        confirmedAt,
        cancelledAt,
        null,
        null,
        null,
        updatedAt,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null, null, null, null, "DIRECT", null, 1);
  }
}
