spring:
  application:
    name: venueflow-resource-service
  profiles:
    default: skeleton
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
#    active: persistence

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
