package com.yanerdan.venueflow.booking.application;

public enum BookingErrorCode {
  BOOKING_VALIDATION_FAILED,
  BOOKING_IDEMPOTENCY_CONFLICT,
  BOOKING_REQUEST_IN_PROGRESS,
  BOOKING_NOT_FOUND,
  BOOKING_USER_NOT_ELIGIBLE,
  BOOKING_CAPACITY_UNAVAILABLE,
  BOOKING_DOWNSTREAM_UNAVAILABLE,
  BOOKING_ALLOCATION_OUTCOME_UNKNOWN,
  BOOKING_PERSISTENCE_FAILED,
  BOOKING_COMPENSATION_REQUIRED,
  BOOKING_STATE_CONFLICT
}
