spring:
  application:
    name: venueflow-notification-service
  profiles:
    default: skeleton
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

server:
  port: ${SERVER_PORT:8085}

management:
  opentelemetry:
    enabled: false
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health
      discovery:
        enabled: false
    jmx:
      exposure:
        exclude: "*"

  endpoint:
    health:
      access: read-only
      show-details: never
      show-components: never
      probes:
        enabled: true
